### PR TITLE
Set backtrace when re-raising exception

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by segiddins** [comment]
@alloy, any chance of getting this merged & released?

**Comment by alloy** [comment]
Oh, hadn’t seen this, thanks for ping.

**Comment by alloy** [comment]
Makes sense to me 👍

**Comment by alloy** [comment]
Pushed. Let me know if adding you as a gem owner is helpful.

**Comment by segiddins** [comment]
Thanks!

**Pull request merged**
